### ISSUE TITLE
PDOException with message Column not found

### ISSUE THREAD

**Issue by deconya** [centreon/nagiosToCentreon#31]
Hi
Im checking to import centreon 2.3.3 to last version, importing all config (In this case centreon was a frontend from nagios, after that they changed all the schema) . The export part seems to work nice, but when I import  I receive this log
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'host_parents' in 'field list'' in /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /usr/share/centreon/lib/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/share/centreon/lib/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
#3 /usr/share/centreon/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE host SET...', Array)
#4 /usr/share/centreon/lib/Centreon/Object/Object.php(196): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE host SET...', Array)
#5 /usr/share/centreon/www/class/centreon-clapi/centreonObject.class.php(269): Centreon_Object->update('109', Array)
#6 /usr/share/centreon/www/class/centreon-clapi/centreonHost.class.php(439): CentreonClapi\CentreonObject->setparam('109', Array)
#7 /usr/share/centreon/www/class/centreon- in /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php on line 234

I don't know where to check this error.

**Comment by deconya** [comment]
Seems to ve duplicated with #22 so I will check patch 
Thx

**Comment by deconya** [comment]
Patched seems that scripts works, but only migrate enabled objects, not all. Any form to include disabled objects?
